### ISSUE TITLE
SEP V021: Unspecified Interaction Glyph Node

### ISSUE THREAD

**Issue by Randoom97** [SynBioDex/SBOL-visual#102] opened 2020-09-04 17:18 UTC
This SEP proposes a way to visualize interactions where the nature of the interaction is unknown by adding a new "unspecified" interaction node glyph.
Read the full SEP at: https://github.com/SynBioDex/SBOL-visual/blob/SEP-V021/SEPs/SEP_V021.md

**Comment by jakebeal** [comment] 2020-09-04 18:12
Lines without arrowheads are already being used in SBOL Visual to indicate mapping relationships.  In terms of the data model, in SBOL 2, this is MapsTo relations and in SBOL 3 this is identity constraints.

Could we instead put a different arrowhead on?
Here I might suggest using the "unspecified" glyph that we have used in other places to indicate a lack of knowledge: 
![unspecified glyph](https://github.com/SynBioDex/SBOL-visual/blob/master/Glyphs/FunctionalComponents/unspecified/replacement-glyph-specification.png?raw=true)

**Comment by cjmyers** [comment] 2020-09-04 19:00
The problem is we do not even know the direction.  We would need to put this on every end of the connection.  

I thought with MapsTos, we agreed these would be dashed.  I know you consider that a styling, but I thought this was the one place we agreed that it could be meaningful to be dashed.

**Comment by jakebeal** [comment] 2020-09-04 19:23
Dashes are a "SHOULD", not a "MUST". That "SHOULD", however, reflects the fact that a solid line can already be visually confused with other drawing elements such as module boundaries, backbones, and the incoming edge for an interaction node.

Interaction nodes, however, may provide a solution path of their own.  Rather than putting something at the end of an edge, why not put it in the middle as an interaction node?  That would also allow multi-way interactions of unknown role, e.g., 
![image](https://user-images.githubusercontent.com/10675899/92278121-2298fa00-eeba-11ea-8470-ca3d45ecc9a2.png)

**Comment by cjmyers** [comment] 2020-09-04 19:27
This could work, and it is certainly visibly clear that there is a problem.  @Randoom97 what do you think?  Would this be easy to include in SBOLCanvas?

**Comment by Randoom97** [comment] 2020-09-04 19:36
I still need to add interaction glyph nodes anyway. I don't see this being too much of a stretch from that.

**Comment by jakebeal** [comment] 2020-09-04 19:38
Great: can you adjust the SEP accordingly, write up the spec and glyph diff on a branch, and socialize it further on the SBOL Visual mailing list?

**Comment by jakebeal** [comment] 2020-10-09 13:12
The ready-to-vote version of this SEP is at: https://github.com/SynBioDex/SBOL-visual/blob/bd51b2eb31e64d314b10ef380cc46f2f63be3f87/SEPs/SEP_V021.md

This is part of a pending pull request, which should not be merged until approval: https://github.com/SynBioDex/SBOL-visual/pull/108

**Comment by jakebeal** [comment] 2020-11-05 21:16
Closing as accepted and incorporated.

**Closed as completed by jakebeal** 2020-11-05 21:16 UTC
Labels: SEP, Accepted, final
